### ISSUE TITLE
Phenotrex Installation help 

### ISSUE THREAD

**Issue by sagrant** [LokiLuciferase/phenotrex#7]
So I'm a bit of a bioinformatics newbie, I'm trying to find a good program to infer microbial phenotypes based on FASTA files. Phenotrex seems to provide exactly what I want but I can't make it run, I suspect because it's not installed entirely correctly. 

When I run the command: 
`phenotrex compute-genotype --out Pse_aerug Pseudomonas_aeruginosa.fna`

I get the error message:
`ModuleNotFoundError: No module named 'deepnog.models.deepencoding'`

Indeed, I cannot find this module in the deepnog models folder but I can't figure out how to install it correctly. Any help would be greatly appreciated! Thanks!

**Comment by LokiLuciferase** [comment]
Hi @sagrant ,

Very sorry for the late response, for some reason I did not have mail notifications configured for this repo.

There was an issue with the package requirements (some package versions had to be pinned).
I have recently released a new version (v0.6.0) to PyPI which fixes this issue. I have also created a follow along tutorial here: https://phenotrex.readthedocs.io/en/latest/usage.html , installation and usage should be covered by this.

Just let me know if you need any further help.
