### ISSUE TITLE
Classifier for all phenotypes

### ISSUE THREAD

**Issue by susheelbhanu** [LokiLuciferase/phenotrex#9]
Hi, 

I am currently using the `classifiers` provided by the tool. And I noticed that from the basic usage that one has to run each classifier individually.

Is it possible to run multiple or all classifiers at the same time? If yes, could you please provide an example syntax?

Thank you,
Susheel

**Comment by LokiLuciferase** [comment]
Hi again,

Currently this functionality is not implemented. If you intend to use the classifiers which can be downloaded on `phendb.org/download`, you could simply submit your bins to `https://phen.csb.univie.ac.at/phendb/` which runs processing for you in parallel and lets you download the results afterwards.

To run it locally (e.g. with custom models or to integrate in a workflow), If you are comfortable with writing a bit of python, you could relatively easily write a small script which implements this. Check out the function `phenotrex.ml.prediction.predict` which basically implements the whole functionality for the `phenotrex predict` CLI interface.

I acknowledge that for CLI usage this functionality would be desirable, and I'll add this when I have time, but unfortunately I can't promise when that will be :)

best
Lukas

**Comment by susheelbhanu** [comment]
Awesome, thank you. I sure can integrate it into a snakemake workflow as a workaround. Will look forward to the new functionality, if and when you get around to it ;). 

Thanks again!
Susheel
